name: Kitpvp-Invclear
version: 1.0.0
main: org.pixel.kitpvpinvclear.Main
api-version: 1.16
authors: [ PixelAgent007 ]
description: Clears Inventory on Death for KitPVP. Requires Gamerule keepInventory set to true.
